name: roottestenv
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.1=py37_0
  - afterimage=1.21=h37b8349_1003
  - astor=0.8.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bayesian-optimization=1.0.1=py_0
  - binutils-meta=1.0.4=0
  - binutils_impl_linux-64=2.33.1=he1b5a44_7
  - binutils_linux-64=2.33.1=h9595d00_15
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - bzip2=1.0.8=h516909a_2
  - c-ares=1.15.0=h7b6447c_1001
  - c-compiler=1.0.4=h516909a_0
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py37_0
  - cfitsio=3.470=hb60a0a2_2
  - compilers=1.0.4=0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cupti=10.0.130=0
  - curl=7.65.3=hf8cf82a_0
  - cxx-compiler=1.0.4=hc9558a2_0
  - cycler=0.10.0=py_2
  - davix=0.7.5=hb54d6fb_1
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - eli5=0.10.1=py37_1
  - entrypoints=0.3=py37_0
  - expat=2.2.5=he1b5a44_1004
  - fftw=3.3.8=nompi_h7f3a6c3_1110
  - fontconfig=2.13.1=h86ecdb6_1001
  - fortran-compiler=1.0.4=he991be0_0
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h516909a_1002
  - gast=0.2.2=py37_0
  - gcc_impl_linux-64=7.3.0=habb00fd_2
  - gcc_linux-64=7.3.0=h553295d_15
  - gdk-pixbuf=2.36.12=haf2c3b9_1004
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.3.0=hdf63c60_2
  - gfortran_linux-64=7.3.0=h553295d_15
  - giflib=5.1.7=h516909a_1
  - glew=2.0.0=he1b5a44_1003
  - glib=2.63.1=h5a9c865_0
  - gobject-introspection=1.58.2=py37h5503ade_1002
  - google-pasta=0.1.8=py_0
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.42.3=h0511662_0
  - grpcio=1.16.1=py37hf8bcb03_1
  - gsl=2.5=h294904e_1
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_2
  - gxx_linux-64=7.3.0=h553295d_15
  - h5py=2.9.0=py37h7918eee_0
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=64.2=he1b5a44_1
  - intel-openmp=2019.5=281
  - ipykernel=5.1.3=py37h39e3cac_0
  - ipyparallel=6.2.4=py37_0
  - ipython=7.10.2=py37h39e3cac_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=2.6.0=py37_0
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.1=py37_0
  - keras=2.2.4=py37_1
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py37_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37he6710b0_0
  - krb5=1.16.4=h2fd8d38_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=7_h6e990d7_netlib
  - libcblas=3.8.0=7_h6e990d7_netlib
  - libclang=9.0.0=default_hde54327_4
  - libcroco=0.6.13=h8d621e5_0
  - libcurl=7.65.3=hda55be3_0
  - libcxx=9.0.0=hc9558a2_1
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_2
  - libglu=9.0.0=hf484d3e_1000
  - libgpuarray=0.7.6=h14c3975_1003
  - libiconv=1.15=h516909a_1005
  - libllvm9=9.0.0=hc9558a2_3
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.11.2=hd408876_0
  - librsvg=2.46.4=h33a7fed_0
  - libsodium=1.0.17=h516909a_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_0
  - libtiff=4.1.0=hc3755c2_1
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.9.1=hebb1f50_0
  - libxml2=2.9.10=hee79883_0
  - lz4=2.2.1=py37h7b6447c_0
  - lz4-c=1.8.3=he1b5a44_1001
  - mako=1.1.0=py_0
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.2=py37_1
  - matplotlib-base=3.1.2=py37h250f245_1
  - metakernel=0.24.3=py_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2018.0.3=1
  - more-itertools=8.0.2=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - notebook=6.0.2=py37_0
  - nspr=4.24=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.16.2=py37h7fc5cc3_0
  - openssl=1.1.1=h7b6447c_0
  - opt_einsum=3.1.0=py_0
  - pandas=0.25.3=py37he6710b0_0
  - pandoc=2.9.1=0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=ha030887_1
  - parso=0.5.2=py_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=he1b5a44_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - portalocker=1.5.2=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - protobuf=3.11.2=py37he6710b0_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pydot=1.4.1=py37_0
  - pygments=2.5.2=py_0
  - pygpu=0.7.6=py37hc1659b7_1000
  - pyparsing=2.4.6=py_0
  - pyqt=5.12.3=py37hcca6a23_1
  - pythia8=8.240=py37he1b5a44_3
  - python=3.7.6=h357f687_1
  - python-dateutil=2.8.1=py_0
  - python-graphviz=0.13.2=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.2=py37h7b6447c_0
  - pyzmq=18.1.0=py37he6710b0_0
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=hf8c457e_0
  - root=6.18.00=py37h2d969ba_18
  - root_numpy=4.8.0=py37h9de70de_2
  - scikit-learn=0.19.1=py37hedc7406_0
  - scipy=1.1.0=py37hfa4b5c9_1
  - seaborn=0.9.0=pyh91ea838_1
  - send2trash=1.5.0=py_0
  - setuptools=42.0.2=py37_0
  - singledispatch=3.4.0.3=py37_1000
  - six=1.13.0=py37_0
  - sqlite=3.30.1=hcee41ef_0
  - statsmodels=0.10.1=py37hdd07704_0
  - tabulate=0.8.6=py_0
  - tbb=2019.9=hc9558a2_1
  - tbb-devel=2019.9=hc9558a2_1
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=2.0.0=gpu_py37h768510d_0
  - tensorflow-base=2.0.0=gpu_py37h0ec5d1f_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - tensorflow-gpu=2.0.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - theano=1.0.4=py37hf484d3e_1000
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.3=py37h7b6447c_0
  - traitlets=4.3.3=py37_0
  - vdt=0.4.3=he1b5a44_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxcursor=1.2.0=h516909a_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxft=2.3.3=h71203ad_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xrootd=4.10.1=py37h997b6ef_0
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h96e3832_1
  - zeromq=4.3.2=he1b5a44_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: /hpcfs/bes/mlgpu/kapoor/anaconda3/envs/roottestenv

